services:
  # smtp:
  #   image: mailhog/mailhog
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8989:8989"
      - "25:25"
    # depends_on:
    #   - redis
    environment:
      - REDIS_URL=redis://default:15qSTCSAaTCVpVz7uJZvsicPPTQZEaHk9VBJ5s3GBGaS1QwbvTIp5px0QXMS9Neo@139.59.69.206:6379/0
      - REDIS_HOST=139.59.69.206
      - REDIS_PORT=6379
      - REDIS_PASSWORD=15qSTCSAaTCVpVz7uJZvsicPPTQZEaHk9VBJ5s3GBGaS1QwbvTIp5px0QXMS9Neo
      - REDIS_DB=0
      

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redis-data:/data

# volumes:
#   redis-data:


